version: '3'

services:
  universe:
    image: 'universe'
    container_name: 'universe'
    restart: always
    environment:
      - DOCKER_NET_HOST=172.12.0.1
      - DGROUP=997
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "12345:12345"
      - "5900:5900"
      - "5901:5901"
    volumes:
      - /home/jon/.mujoco:/home/universe/.mujoco
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.backend=universe
      - traefik.docker.network=proxy
      - traefik.enable=true
      - traefik.frontend.rule=Host:universe.stizz.net
      - traefik.ssl.port=12345
      - traefik.ssl.protocol=https
      - traefik.frontend.entryPoints=https,http 
      - traefik.http.port=12346
      - traefik.http.protocol=http
    tty: true
    cap_add: 
      - NET_ADMIN
    networks:
      swarmProxy:

networks:
  swarmProxy:
    external: True
